import { ClassificationLevel } from "../types";

export const classificationLevels: ClassificationLevel[] = [
  // --- [초급: 원색으로 손풀기 & 마진 좁히기] ---
  {
    level: 1,
    type: "drag_sort",
    objectCount: 1,
    targetCount: 1,
    colorPool: "primary",
    margin: 50,
    features: {
      color: true,
      shape: false,
      size: false,
      number: false,
      hat: false,
      pattern: false,
      category: false,
    },
    rule: "color_classification",
  },
  {
    level: 2,
    type: "drag_sort",
    objectCount: 1,
    targetCount: 1,
    colorPool: "all",
    margin: 35,
    features: {
      color: true,
      shape: false,
      size: false,
      number: false,
      hat: false,
      pattern: false,
      category: false,
    },
    rule: "color_classification",
  },
  {
    level: 3,
    type: "drag_sort",
    objectCount: 1,
    targetCount: 1,
    colorPool: "pastel",
    margin: 20,
    features: {
      color: true,
      shape: false,
      size: false,
      number: false,
      hat: false,
      pattern: false,
      category: false,
    },
    rule: "color_classification",
  },
  {
    level: 4,
    type: "drag_sort",
    objectCount: 2,
    targetCount: 1,
    colorPool: "primary",
    margin: 20,
    features: {
      color: true,
      shape: false,
      size: false,
      number: false,
      hat: false,
      pattern: false,
      category: false,
    },
    rule: "color_classification",
  },
  {
    level: 5,
    type: "drag_sort",
    objectCount: 2,
    targetCount: 1,
    colorPool: "all",
    margin: 10,
    features: {
      color: true,
      shape: false,
      size: false,
      number: false,
      hat: false,
      pattern: false,
      category: false,
    },
    rule: "color_classification",
  },
  {
    level: 6,
    type: "drag_sort",
    objectCount: 2,
    targetCount: 1,
    colorPool: "pastel",
    margin: 0,
    features: {
      color: true,
      shape: false,
      size: false,
      number: false,
      hat: false,
      pattern: false,
      category: false,
    },
    rule: "color_classification",
  },

  // --- [중급: 오브젝트 3개 확장 & 색상 심화] ---
  {
    level: 7,
    type: "drag_sort",
    objectCount: 3,
    targetCount: 1,
    colorPool: "primary",
    margin: 10,
    features: {
      color: true,
      shape: false,
      size: false,
      number: false,
      hat: false,
      pattern: false,
      category: false,
    },
    rule: "color_classification",
  },
  {
    level: 8,
    type: "drag_sort",
    objectCount: 3,
    targetCount: 1,
    colorPool: "all",
    margin: 5,
    features: {
      color: true,
      shape: false,
      size: false,
      number: false,
      hat: false,
      pattern: false,
      category: false,
    },
    rule: "color_classification",
  },
  {
    level: 9,
    type: "drag_sort",
    objectCount: 3,
    targetCount: 1,
    colorPool: "pastel",
    margin: 0,
    features: {
      color: true,
      shape: false,
      size: false,
      number: false,
      hat: false,
      pattern: false,
      category: false,
    },
    rule: "color_classification",
  },
  {
    level: 10,
    type: "drag_sort",
    objectCount: 3,
    targetCount: 1,
    colorPool: "all",
    margin: 0,
    features: {
      color: true,
      shape: false,
      size: false,
      number: false,
      hat: false,
      pattern: false,
      category: false,
    },
    rule: "color_classification",
  },

  // --- [상급/마스터: 오브젝트 4개 최대치 & 촘촘한 최종 관문] ---
  {
    level: 11,
    type: "drag_sort",
    objectCount: 4,
    targetCount: 1,
    colorPool: "primary",
    margin: 5,
    features: {
      color: true,
      shape: false,
      size: false,
      number: false,
      hat: false,
      pattern: false,
      category: false,
    },
    rule: "color_classification",
  },
  {
    level: 12,
    type: "drag_sort",
    objectCount: 4,
    targetCount: 1,
    colorPool: "all",
    margin: 0,
    features: {
      color: true,
      shape: false,
      size: false,
      number: false,
      hat: false,
      pattern: false,
      category: false,
    },
    rule: "color_classification",
  },
  {
    level: 13,
    type: "drag_sort",
    objectCount: 4,
    targetCount: 1,
    colorPool: "pastel",
    margin: 0,
    features: {
      color: true,
      shape: false,
      size: false,
      number: false,
      hat: false,
      pattern: false,
      category: false,
    },
    rule: "color_classification",
  },
  {
    level: 14,
    type: "drag_sort",
    objectCount: 4,
    targetCount: 1,
    colorPool: "all",
    margin: 0,
    features: {
      color: true,
      shape: false,
      size: false,
      number: false,
      hat: false,
      pattern: false,
      category: false,
    },
    rule: "color_classification",
  },
  {
    level: 15,
    type: "drag_sort",
    objectCount: 4,
    targetCount: 1,
    colorPool: "pastel",
    margin: 0,
    features: {
      color: true,
      shape: false,
      size: false,
      number: false,
      hat: false,
      pattern: false,
      category: false,
    },
    rule: "color_classification",
  },
];
