import { CategoryLevelConfig } from "../type/types";

export const categoryLevels: CategoryLevelConfig[] = [
  // ── 도입: 오답 없음 ─────────────────────────────────────────
  {
    level: 1,
    mode: "single",
    objectCount: 1,
    targetSlotCount: 3,
    targetColorMode: "same",
    correctObjectMode: "same_as_target",
    rule: "category_classification",
  },
  {
    level: 2,
    mode: "single",
    objectCount: 1,
    targetSlotCount: 3,
    targetColorMode: "natural",
    correctObjectMode: "natural_variant",
    rule: "category_classification",
  },

  // ── L3~L8: TargetBox 완전 동일 + 정답=동일 개체 ────────────────
  {
    level: 3,
    mode: "choice",
    objectCount: 2,
    targetSlotCount: 3,
    targetColorMode: "same",
    correctObjectMode: "same_as_target",
    wrongRelation: "different_category",
    rule: "category_classification",
  },
  {
    level: 4,
    mode: "choice",
    objectCount: 2,
    targetSlotCount: 3,
    targetColorMode: "same",
    correctObjectMode: "same_as_target",
    wrongRelation: "different_subcategory",
    rule: "category_classification",
  },
  {
    level: 5,
    mode: "choice",
    objectCount: 2,
    targetSlotCount: 3,
    targetColorMode: "same",
    correctObjectMode: "same_as_target",
    wrongRelation: "different_type",
    rule: "category_classification",
  },
  {
    level: 6,
    mode: "choice",
    objectCount: 3,
    targetSlotCount: 3,
    targetColorMode: "same",
    correctObjectMode: "same_as_target",
    wrongRelation: "different_category",
    rule: "category_classification",
  },
  {
    level: 7,
    mode: "choice",
    objectCount: 3,
    targetSlotCount: 3,
    targetColorMode: "same",
    correctObjectMode: "same_as_target",
    wrongRelation: "different_subcategory",
    rule: "category_classification",
  },
  {
    level: 8,
    mode: "choice",
    objectCount: 3,
    targetSlotCount: 3,
    targetColorMode: "same",
    correctObjectMode: "same_as_target",
    wrongRelation: "different_type",
    rule: "category_classification",
  },

  // ── L9~L14: TargetBox 자연 변주 + 정답=타겟에 있던 개체 ─────────
  {
    level: 9,
    mode: "choice",
    objectCount: 2,
    targetSlotCount: 3,
    targetColorMode: "natural",
    correctObjectMode: "same_as_target",
    wrongRelation: "different_category",
    rule: "category_classification",
  },
  {
    level: 10,
    mode: "choice",
    objectCount: 2,
    targetSlotCount: 3,
    targetColorMode: "natural",
    correctObjectMode: "same_as_target",
    wrongRelation: "different_subcategory",
    rule: "category_classification",
  },
  {
    level: 11,
    mode: "choice",
    objectCount: 2,
    targetSlotCount: 3,
    targetColorMode: "natural",
    correctObjectMode: "same_as_target",
    wrongRelation: "different_type",
    rule: "category_classification",
  },
  {
    level: 12,
    mode: "choice",
    objectCount: 3,
    targetSlotCount: 3,
    targetColorMode: "natural",
    correctObjectMode: "same_as_target",
    wrongRelation: "different_category",
    rule: "category_classification",
  },
  {
    level: 13,
    mode: "choice",
    objectCount: 3,
    targetSlotCount: 3,
    targetColorMode: "natural",
    correctObjectMode: "same_as_target",
    wrongRelation: "different_subcategory",
    rule: "category_classification",
  },
  {
    level: 14,
    mode: "choice",
    objectCount: 3,
    targetSlotCount: 3,
    targetColorMode: "natural",
    correctObjectMode: "same_as_target",
    wrongRelation: "different_type",
    rule: "category_classification",
  },

  // ── L15~L20: TargetBox 자연 변주 + 정답=완전히 새로운 개체 ──────
  {
    level: 15,
    mode: "choice",
    objectCount: 2,
    targetSlotCount: 3,
    targetColorMode: "natural",
    correctObjectMode: "unseen_variant",
    wrongRelation: "different_category",
    rule: "category_classification",
  },
  {
    level: 16,
    mode: "choice",
    objectCount: 2,
    targetSlotCount: 3,
    targetColorMode: "natural",
    correctObjectMode: "unseen_variant",
    wrongRelation: "different_subcategory",
    rule: "category_classification",
  },
  {
    level: 17,
    mode: "choice",
    objectCount: 2,
    targetSlotCount: 3,
    targetColorMode: "natural",
    correctObjectMode: "unseen_variant",
    wrongRelation: "different_type",
    rule: "category_classification",
  },
  {
    level: 18,
    mode: "choice",
    objectCount: 3,
    targetSlotCount: 3,
    targetColorMode: "natural",
    correctObjectMode: "unseen_variant",
    wrongRelation: "different_category",
    rule: "category_classification",
  },
  {
    level: 19,
    mode: "choice",
    objectCount: 3,
    targetSlotCount: 3,
    targetColorMode: "natural",
    correctObjectMode: "unseen_variant",
    wrongRelation: "different_subcategory",
    rule: "category_classification",
  },
  {
    level: 20,
    mode: "choice",
    objectCount: 3,
    targetSlotCount: 3,
    targetColorMode: "natural",
    correctObjectMode: "unseen_variant",
    wrongRelation: "different_type",
    rule: "category_classification",
  },
];
