//"각 레벨에서 어떤 규칙으로 출제할 것인가?"
import { ShapeLevelConfig } from "../type/types";

export const shapeLevels: ShapeLevelConfig[] = [
  // ==================================================
  // Level 1 ~ 8: Object 1개
  // ==================================================
  {
    level: 1,
    mode: "single",
    objectCount: 1,
    targetSlotCount: 4,
    targetKind: "shape",
    correctKind: "shape",
    targetColorMode: "same",
    correctColorMode: "same_as_target",
    rule: "shape_classification",
  },
  {
    level: 2,
    mode: "single",
    objectCount: 1,
    targetSlotCount: 4,
    targetKind: "shape",
    correctKind: "shape",
    targetColorMode: "different",
    correctColorMode: "not_in_target",
    avoidTargetColors: true,
    rule: "shape_classification",
  },
  {
    level: 3,
    mode: "single",
    objectCount: 1,
    targetSlotCount: 4,
    targetKind: "shape",
    correctKind: "item",
    targetColorMode: "different",
    correctColorMode: "random",
    rule: "shape_classification",
  },
  {
    level: 4,
    mode: "single",
    objectCount: 1,
    targetSlotCount: 4,
    targetKind: "item",
    correctKind: "shape",
    targetColorMode: "same",
    correctColorMode: "same_as_target",
    rule: "shape_classification",
  },
  {
    level: 5,
    mode: "single",
    objectCount: 1,
    targetSlotCount: 4,
    targetKind: "item",
    correctKind: "shape",
    targetColorMode: "same",
    correctColorMode: "random",
    rule: "shape_classification",
  },
  {
    level: 6,
    mode: "single",
    objectCount: 1,
    targetSlotCount: 4,
    targetKind: "item",
    correctKind: "shape",
    targetColorMode: "different",
    correctColorMode: "different_from_target",
    avoidTargetColors: true,
    rule: "shape_classification",
  },
  {
    level: 7,
    mode: "single",
    objectCount: 1,
    targetSlotCount: 4,
    targetKind: "item",
    correctKind: "shape",
    targetColorMode: "natural",
    correctColorMode: "random",
    rule: "shape_classification",
  },
  {
    level: 8,
    mode: "single",
    objectCount: 1,
    targetSlotCount: 4,
    targetKind: "item",
    correctKind: "item",
    targetColorMode: "natural",
    correctColorMode: "natural",
    rule: "shape_classification",
  },
  // ==================================================
  // Level 9 ~ 21: 2지선다
  // ==================================================

  {
    level: 9,
    mode: "choice",
    objectCount: 2,
    targetSlotCount: 4,
    targetKind: "shape",
    correctKind: "shape",
    wrongKind: "shape",
    targetColorMode: "same",
    correctColorMode: "same_as_target",
    wrongColorMode: "same_as_target",
    sameChoiceColor: true,
    rule: "shape_classification",
  },
  {
    level: 10,
    mode: "choice",
    objectCount: 2,
    targetSlotCount: 4,
    targetKind: "shape",
    correctKind: "shape",
    wrongKind: "shape",
    targetColorMode: "different",
    correctColorMode: "not_in_target",
    wrongColorMode: "not_in_target",
    sameChoiceColor: true,
    avoidTargetColors: true,
    rule: "shape_classification",
  },
  {
    level: 11,
    mode: "choice",
    objectCount: 2,
    targetSlotCount: 4,
    targetKind: "shape",
    correctKind: "shape",
    wrongKind: "shape",
    targetColorMode: "different",
    correctColorMode: "not_in_target",
    wrongColorMode: "not_in_target",
    sameChoiceColor: false,
    avoidTargetColors: true,
    rule: "shape_classification",
  },
  {
    level: 12,
    mode: "choice",
    objectCount: 2,
    targetSlotCount: 4,
    targetKind: "shape",
    correctKind: "item",
    wrongKind: "shape",
    targetColorMode: "different",
    correctColorMode: "not_in_target",
    wrongColorMode: "not_in_target",
    sameChoiceColor: true,
    avoidTargetColors: true,
    rule: "shape_classification",
  },
  {
    level: 13,
    mode: "choice",
    objectCount: 2,
    targetSlotCount: 4,
    targetKind: "shape",
    correctKind: "item",
    wrongKind: "shape",
    targetColorMode: "different",
    correctColorMode: "natural",
    wrongColorMode: "not_in_target",
    sameChoiceColor: false,
    avoidTargetColors: true,
    rule: "shape_classification",
  },
  {
    level: 14,
    mode: "choice",
    objectCount: 2,
    targetSlotCount: 4,
    targetKind: "shape",
    correctKind: "item",
    wrongKind: "item",
    targetColorMode: "different",
    correctColorMode: "not_in_target",
    wrongColorMode: "not_in_target",
    sameChoiceColor: true,
    avoidTargetColors: true,
    rule: "shape_classification",
  },
  {
    level: 15,
    mode: "choice",
    objectCount: 2,
    targetSlotCount: 4,
    targetKind: "shape",
    correctKind: "item",
    wrongKind: "item",
    targetColorMode: "different",
    correctColorMode: "natural",
    wrongColorMode: "natural",
    sameChoiceColor: false,
    rule: "shape_classification",
  },
  {
    level: 16,
    mode: "choice",
    objectCount: 2,
    targetSlotCount: 4,
    targetKind: "item",
    correctKind: "shape",
    wrongKind: "shape",
    targetColorMode: "same",
    correctColorMode: "same_as_target",
    wrongColorMode: "same_as_target",
    sameChoiceColor: true,
    rule: "shape_classification",
  },
  {
    level: 17,
    mode: "choice",
    objectCount: 2,
    targetSlotCount: 4,
    targetKind: "item",
    correctKind: "item",
    wrongKind: "item",
    targetColorMode: "same",
    correctColorMode: "same_as_target",
    wrongColorMode: "same_as_target",
    sameChoiceColor: true,
    rule: "shape_classification",
  },
  {
    level: 18,
    mode: "choice",
    objectCount: 2,
    targetSlotCount: 4,
    targetKind: "item",
    correctKind: "shape",
    wrongKind: "shape",
    targetColorMode: "natural",
    correctColorMode: "random",
    wrongColorMode: "same_as_each_other",
    sameChoiceColor: true,
    rule: "shape_classification",
  },
  {
    level: 19,
    mode: "choice",
    objectCount: 2,
    targetSlotCount: 4,
    targetKind: "item",
    correctKind: "item",
    wrongKind: "shape",
    targetColorMode: "natural",
    correctColorMode: "natural",
    wrongColorMode: "random",
    rule: "shape_classification",
  },
  {
    level: 20,
    mode: "choice",
    objectCount: 2,
    targetSlotCount: 4,
    targetKind: "item",
    correctKind: "item",
    wrongKind: "item",
    targetColorMode: "same",
    correctColorMode: "natural",
    wrongColorMode: "natural",
    avoidTargetColors: true,
    rule: "shape_classification",
  },
  {
    level: 21,
    mode: "choice",
    objectCount: 2,
    targetSlotCount: 4,
    targetKind: "item",
    correctKind: "item",
    wrongKind: "item",
    targetColorMode: "natural",
    correctColorMode: "natural",
    wrongColorMode: "natural",
    rule: "shape_classification",
  },
];
